version: '3'
services:
  
  mongodb:
    image: mongo:5.0
    container_name: mongodb-local
    ports:
    - 27017:27017
  express-apibase:
    image: apibase:1.0
    container_name: apibase-container
    environment: 
      - MONGODB_CONNSTRING=mongodb://192.168.56.1:27017/Tododb
    ports:
      - 4000:4000
  front-react:
    image: frontglobo:1.0
    container_name: frontglobo-container
    ports:
    - 3000:3000
    